# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='status',
            field=models.CharField(choices=[('A', 'Online'), ('B', 'Offline5lower'), ('C', 'Offline5greater')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ip_adress',
            field=models.CharField(default='somestring', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(default='somestring', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(default='somestring', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='somestring', max_length=100),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='production_date',
            field=models.CharField(default='somestring', max_length=15),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='sim_card_number',
            field=models.CharField(default='somestring', max_length=20),
        ),
    ]
