# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20170621_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.Site'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='accesspoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.Accesspoint'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='production_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='sim_card_number',
            field=models.CharField(default='missing sim', max_length=20),
        ),
    ]
